name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Print repo root contents (debug)
        run: |
          echo "=== ls -R (top level) ==="
          ls -al
          echo "=== node/version ==="
          node --version || echo "node not installed"
          echo "=== npm version ==="
          npm --version

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Show build script and package.json snippet (debug)
        run: |
          echo "--- package.json scripts ---"
          jq '.scripts' package.json || cat package.json | head -n 60

      - name: Build
        run: npm run build

      - name: Inspect dist folder (debug)
        run: |
          echo "=== dist contents ==="
          ls -R dist | head -100

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          cname: www.nvskumar.com
